//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madplan.ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietPlans
    {
        public System.Guid UserId { get; set; }
        public int RecipeId { get; set; }
        public System.DateTime Date { get; set; }
        public int Id { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
