//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Madplan.ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodplanEntities : DbContext
    {
        public FoodplanEntities()
            : base("name=FoodplanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<DietPlans> DietPlans { get; set; }
        public DbSet<FoodProduct> FoodProduct { get; set; }
        public DbSet<Recipe> Recipe { get; set; }
        public DbSet<Userdata> Userdata { get; set; }
    }
}
